### ISSUE TITLE
Manage API Token

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#126]
**Is your feature request related to a problem? Please describe.**

Right now API Tokens are stored in the [User model](https://github.com/jointwt/twtxt/blob/master/internal/models.go#L54) just simple as a list of strings. This isn't great for a number of reasons as we can't easily store any additional data on the token without decrypting the entire JWT such as the expiry date/time or the device / user-agent, and this list is currently unbounded.

**Describe the solution you'd like**

We need to define a new model for storing and managing API Tokens, let's called it `Token` which at a minimum stores:

- `Value` -- The actual JWT token value which stored encrypted/signed data as given to the client using it.
- `UserAgent` -- The name of the client and version number that initially created the token.
- `CreatedAt` -- The date/time the token was created
- `ExpiresAt` -- The date/time the token expires (_if ever_)

In the [/settings](https://twtxt.net/settings) view for user accounts on [Twt.social](https://twt.social) pods we want to be able to:

- List the currently in-use API Tokens associated with the user's account
- Allow the user to delete tokens

Additionally there should be a background job, let's call it `DeleteOldTokensJob` that:

- Iterates over all stored tokens
- Checks if any have expired (_if any_)
- Deletes any expired tokens

**Describe alternatives you've considered**

N/A - The current implementation sucks.

**Additional context**

N/A -- Open to other ideas for token management, but this is the basics we need.

**Comment by danielcooperxyz** [comment]
I have a set of changes for this, the last thing left is the deleting of tokens. I believe there would need to be the inclusion of an identifier for the tokens, to provide a RESTful delete endpoint, alternatively a POST endpoint receiving the token value via HTTPS would be enough to find and remove the token from the user data. I think I prefer the former over the latter. Personally I would use a uuid v4 from https://github.com/satori/go.uuid, but is there a preferred way of doing this in this case?

**Comment by prologic** [comment]
Hello @danielcooperxyz ! 👋 Thank you for working on this 🙇‍♂️ This is awesome! 😊

Now you _shoud_ be able to use the underlying `jwt.Token`'s hash itself as the key IHMO. I would expect there to be (_haven't looked at your PR yet_) a new model like:

```#!go
type Token struct  {
  User string `json:"user"` // `User` this token belongs to.
  Value string `json:"value"` // Raw JWT Token value
  CreatedAt time.Time
  ExpiresAt time.Time
}
```

🤔

**Comment by prologic** [comment]
And for these `Token`(s) to be stored along a key prefix of `/tokens/<sha>`. You will also need a mapping of user -> token(s) but you can probably just reuse the `User.Tokens` list I _think_ as a foreign key id into the list of `Token`(s)?

**Comment by danielcooperxyz** [comment]
Thanks for the feedback! I will have a dig and see what I come up with :)

**Comment by danielcooperxyz** [comment]
It currently looks like there is no expiry on the tokens?

**Comment by danielcooperxyz** [comment]
I believe the token expiry needs adding as another claim when creating the token, so this could be added to the model when that expiry claim is added to avoid scope creep in this issue.

**Comment by prologic** [comment]
To be honest I'm not eevne sure if tokens should expire. We have to take into account #139 too

**Comment by lwojcik** [comment]
In almost all OAuth implementations I've seen so far tokens are designed to be temporary - they expire after certain time (e.g. [Battle.net API expires tokens after 24 hours](https://develop.battle.net/documentation/guides/using-oauth)) or due to external events (manual reset, password change, account deletion etc.). Unexpirable tokens may pose a security risk if they get into wrong hands (what if someone consumes API directly in a web browser?). IMO apps should be required to reauthenticate once in a while if their tokens expire and it's possible to automate this.

However, until OAuth-like authorization flow is implemented I don't think expiring tokens is necessary.
