### ISSUE TITLE
Logged out on profile page, logged in everywhere else

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#142]
**Describe the bug**
I suspect it's a unicorn bug unique to my environment, but I'll leave it here, assign to myself and try to deal with it when I have spare cycles.

When I log in, I can move between main page, Discover and Mentions just fine. However, when I go to any profile page (e.g. [here](https://lukestestpod.twt.social/user/luketester)), it loads as if I wasn't logged in. It doesn't recognize my theme settings and I can see 'Login / register' links on top right.

Doesn't apply to Firefox or Brave on Android.

**To Reproduce**
1. Log in
2. Go to main page / Discover / Mentions
3. Go to profile page
4. If you normally use dark theme, I apologize. I know it hurts.

**Expected behavior**
Profile pages should recognize me as a logged in user just like any other section of the site.

**Screenshots**
I can't. I'm blind due to unexpected flash of light theme. :)

**Desktop (please complete the following information):**
 - OS: latest Ubuntu LTS
 - Browser: Chrome (both normal and incognito mode)
 - Version: latest

**Additional context**
Normally I'd suspect one of my privacy-focused Chrome extensions to be doing something stupid, but the fact I can see this bug in incognito mode (e.g. no third party extensions active) baffles me a bit.

**Comment by prologic** [comment]
Fixed by 93732261f7c5c6221cf77de7ed069320593be86e fc496e8de300509e87a2af9bf43179b64a9875d2 and e93ec2a1709d12dbf08a903016132d9c8afbf7ff 😀

**Comment by lwojcik** [comment]
Reopening because the update doesn't seem to have fixed the issue for me.

Even if it's something super specific to the machine I use, I believe there's non-zero possibility it may happen to somebody else.

I'll try to diagnoze this.

**Comment by prologic** [comment]
Thanks! Its possible i missed something non-obvious. LMK!

**Comment by lwojcik** [comment]
I deleted cookies manually from devtools and it fixed itself. Yay!

**Comment by prologic** [comment]
Yeah it was a bit buggy before so hopefully clearing out invalid/bad cookies helped!
