### ISSUE TITLE
Faulty pod on the list

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#146]
**Describe the bug**
There are two test pods of mine on [the pod list](https://twt.social/join).

[This one](https://lukestestpod.twt.social/) is the one I've been using to develop twt.js and I want it to stay.

However, [this one](https://luke%27s%20test%20pod.twt.social/) is an unwanted child. :)

**To Reproduce**
See the links above.

**Expected behavior**
* I shouldn't be able to create pods with faulty names (containing anything but letters, digits and dashes)
* The faulty pod I pointed above should get removed
* While setting up the pod I need clear information how the pod name should look like. While setting up a faulty one I thought it was a display name, not a subdomain name. Maybe adding one more field to the signup form (subdomain name + display name) would do the job?

**Screenshots**
[See image](https://i.imgur.com/T5s0xXm.png)

**Additional context**
Apparently pods were created successfully even though I saw error messages while trying to spawn them:

https://dev.twt.social/twt/l4ojyfsj6sq
https://dev.twt.social/twt/vq7wkxrh3aq

**Comment by prologic** [comment]
Fixed and removed the faulty pod.

It is no longer possible to create such a pod.

I will re-jig the form to be a bit more friendly.

**Comment by prologic** [comment]
And that's been done too.

I'll close this now, but there is much to do here obviously. Like adding some JavaScript validation would be nice.
