### ISSUE TITLE
Delete feed twts 

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#148]
**Is your feature request related to a problem? Please describe.**
When I post as myself, I can edit / delete my latest twt just fine.

When I post as from a feed I own, I can't.

**Describe the solution you'd like**
Deleting / editing twts posted in the feed I own should be possible on the same terms as for twts posted as me. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by prologic** [comment]
Yeah this is entirely missing. Can you implement it? All the code is there to do it :)

**Comment by prologic** [comment]
And I _think_ this is just missing functionality on the backend IHMO.

**Comment by lwojcik** [comment]
I found this: https://github.com/jointwt/twtxt/blob/master/internal/handlers.go#L706

And this: https://github.com/jointwt/twtxt/blob/master/internal/templates/_partials.html#L81

I feel this is something very simple to do but I'm still very noob at Go and failing to notice moving parts.

**Comment by prologic** [comment]
Yeah so I _guess_ that's what I hadn't added this yet, it was simple enough to do it for the user's primary feed (_their username_) by showing the Twt's hash and Text as `data-` attrs like:

```#!html
            [<a class="edit" href="#" data-hash="{{ $.Twt.Hash }}" data-text="{{ $.Twt.Text }}">Edit</a>]
            [<a class="delete" href="#" data-hash="{{ $.Twt.Hash }}">Delete</a>]
```

And then there's just some very simple JS that deals with this like:

https://github.com/jointwt/twtxt/blob/611bed665d0ee06666d22bfed8938fb51c8ec6de/internal/static/js/99-twtxt.js#L145-L179

**Comment by prologic** [comment]
Doing this for deletion is okay, but I'm not sure how to do this for "edits". Maybe instead of storing the content in the `data-text` attr, just store the hash as well and just make an AJAX call to get the `LastTwt()`?

**Comment by prologic** [comment]
I _believe_ this was done with #149 (_but was not linked in the PR_)
