### ISSUE TITLE
Reply link seems to get the last string in parentheses 

### ISSUE THREAD

**Issue by aaadonai** [jointwt/twtxt#153]
**Describe the bug**
When the user hits the reply link and the post has content between parentheses which twtxt uses to refer the "conversation", the feature is getting the last content between parentheses when the post has multiple parentheses. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a post with multiple parentheses (here is [one](https://twtxt.net/twt/624dgdme2cq))
2. Click on `Reply`
3. Observe

**Expected behavior**
It should get the first content between parentheses (the one with the `#` character) instead of the last.

**Screenshots**
![](https://i.imgur.com/9FoLFbD.png)
*Post with multiple parentheses*
![](https://i.imgur.com/AutfyWN.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Chrome 84.0.4147.135 (Official Build) (64-bit)

**Comment by prologic** [comment]
Oh good catch!

Can you fix this? Should be easy to fix by adjusting the following section of code:

https://github.com/jointwt/twtxt/blob/0282f72b922ef98cf9b153d094b0adce26215584/types/twt.go#L63-L71

**Comment by prologic** [comment]
This [online tool](https://regoio.herokuapp.com/) _may_ help fix the Regex too. I'm not actually really sure what's wrong with the regex or the method per se, If you can fix this I'll review/approve and merge it!
