### ISSUE TITLE
Missing OP's username when you hit 'Reply' button

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#162]
**Describe the bug**
In a previous, pre-Conversations iteration of replies, replying to someone would put their username in twt content and thus drawing attention (hey, someone mentioned me, let's see what's up!) + putting the twt in their mentions.

In a post-Conversations iteration, when I hit 'Reply' I can only see a generated hashtag which is very hard for me to associate with my own twt and no username of the original poster. Even if I know the hashtag is derived from my twt permalink, my peanut brain simply isn't trained to treat randomly generated strings as meaningful messages. 'Conversation' link is a step in a right direction as it groups replies in a single view, but it effectively adds another step in the process and another context to keep track of if I don't want to miss interesting takes on my content.

**To Reproduce**
Reply to someone's twt.

**Expected behavior**
Original poster's username should be added to replies.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 Any

**Smartphone (please complete the following information):**
 Any

**Additional context**
I'm open to discussion about this one. I might be overlooking design details which led to Conversations working that way and I'm okay to change my mind / habits.

**Comment by prologic** [comment]
> Original poster's username should be added to replies.

I _removed_ this because I didn't think it was necessary now. But I see your point. Easy to add it back!

**Comment by prologic** [comment]
> I'm open to discussion about this one. I might be overlooking design details which led to Conversations working that way and I'm okay to change my mind / habits.

Nope, it's perfectly "legal" in a syntactic sense for there to be `@mention`(s) at the beginning as well as the Twt's Subject (_which in this case is the conversation hashtag_).

**Comment by prologic** [comment]
Fixed by #163 163
