### ISSUE TITLE
[Browser Extension]: Twt Share

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#165]
Let's build a browser extension for Chrome and Firefox (_yes most people these days use native apps, but nonetheless I would find and I assume others too this a useful little thing to have on my browser's toolbar and it would be a good use-case for [Twt.js](https://github.com/jointwt/twt.js)_).

It should basically have the following featureset:

- A welcome view with a little blurg about what it does with a Pod URL, Username and Password field to login to a Pod.

> Not having ever written a Browser Extension myself, I'm not sure what's possible; However here's the use case:

As a Twt.social user, I would like to occasionally be able to click on my Twt button in my toolbar (_Twt Share_) which pops open a small window with the link to the website already pre-filled (_in Markdown_) and give me an opportunity to write a little extra about it (_if I want_) and hit "Post".

That's it :) Simple and it gives me a nice way to quickly share links to interesting things from Desktop Browsers with people I care about on Twt.social :)

**Comment by lwojcik** [comment]
Boilerplates that make it possible to target Chrome and Firefox with a single codebase are available.

I'll explore this.

**Comment by prologic** [comment]
@lwojcik How is this coming along ? :D

**Comment by lwojcik** [comment]
Going slower than I planned but we have a boilerplate done and implementation should be fairly easy. I'll try to present something usable within 2-3 weeks.

**Comment by prologic** [comment]
Okay I figured out a _slightly_ different way to do this via Bookmarklet(s).

Add the following piece of Javascript to your Web Browser's Bookmark Bar:

```javascript
javascript:(function()%7Bwindow.location.href%3D"https%3A%2F%2Ftwtxt.net"%2B"%2F%3Ftitle%3D"%2Bdocument.title%2B"%26url%3D"%2Bdocument.URL%3B%7D)()%3B
```

And change the Pod URL to suit (_defaults to twtxt.net_).

Or drag [this](javascript:(function()%7Bwindow.location.href%3D"https%3A%2F%2Ftwtxt.net"%2B"%2F%3Ftitle%3D"%2Bdocument.title%2B"%26url%3D"%2Bdocument.URL%3B%7D)()%3B) to your Bookmark Bar.

https://github.com/jointwt/twtxt/commit/67d6b6f5a76a006a99c1b646904f9920c64bde0a added this support.
