### ISSUE TITLE
Duplicate usernames when replying to somebody else's reply to themselves

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#167]
**Describe the bug**
Title says it all. See the next paragraphs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a twt whose author is replying to their own twt, including their username - ([example](https://twtxt.net/twt/6ckllkq))
2. Click 'Reply'
3. Textarea contains duplicated author's username + hashtag.

**Expected behavior**
Author's username should appear only once in the textarea.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 Any

**Smartphone (please complete the following information):**
 Any

**Additional context**
N/A

**Comment by prologic** [comment]
I'm actually a little confused on this one. There is already code to handle deduplication:

https://github.com/jointwt/twtxt/blob/9a67481ebb5e6d97495e7b0bddc567f08fcee774/types/twt.go#L38-L54

I _also_ cannot repro this exactly as you describe locally :/

**Comment by lwojcik** [comment]
Maybe it's a caching issue again? I can reproduce it consistently on Twtxt.net on any browser including incognito mode.

**Comment by prologic** [comment]
Yeah I believe you I'm just having trouble reproducing this myself. Hmmm 🤔

**Comment by prologic** [comment]
Do you think you could create such an example Twt that consists a reply to yourself so I can try this the other way around? It's just a _hunch_...

**Comment by lwojcik** [comment]
[There you go](https://twtxt.net/twt/n5j7vya)

Be sure you test on twts written and replied to by somebody else. From what I noticed de-duplication seems to be working fine if you reply to your own twts but not when you react to other people's twts.

**Comment by prologic** [comment]
Brilliant! It repro'd!

<img width="465" alt="Screen Shot 2020-09-05 at 22 02 51" src="https://user-images.githubusercontent.com/1290234/92304702-970b9000-efc3-11ea-8b37-b70a979e6ed5.png">

🎉
