### ISSUE TITLE
Post-process Twts from external feeds and link tags

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#177]
**Is your feature request related to a problem? Please describe.**

ssia

**Describe the solution you'd like**

Example can be found [here](https://twtxt.net/twt/32mwi6q)

The hashtag there _should_ be linked.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by theamazingeagle** [comment]
![Screenshot_2020-10-24_21-21-35](https://user-images.githubusercontent.com/1557044/97089359-d8bdcc00-163f-11eb-86db-57f02317b0bf.png)
I have deployed app locally, and this issue not reproduced

**Comment by prologic** [comment]
In order to reproduce this, you have to actually have an external feed (one that doesn't use the jointwt/Twtxt backend)

For example here's how you can test this:

1) Setup a simple nginx container or server somewhere
2) Place a twtxt.txt file there
3) Add a line (a Twt) that has a #hashtag in it
4) Observe (once you follow the feed from your local Twtxt pod) that the #hashtag is not rendered as a link

On a Pod or cross-pod(s) this works just fine :) External (legacy if you will) feeds it does not.

**Comment by prologic** [comment]
Fixed by #261
