### ISSUE TITLE
Add video/audio support with embedded player

### ISSUE THREAD

**Issue by aaadonai** [jointwt/twtxt#182]
**Describe the solution you'd like**

Ability to add videos as a first-class post media with a embedded player.

**Describe alternatives you've considered**
Today anyone can link a video on twtxt but that will take the user to a new tab. This feature would allow users to play the video without leaving the twtxt.

**Additional context**

N/A

**Comment by prologic** [comment]
We'll _think_ about "Video Uploads / Hosting" a bit later :)

**Comment by prologic** [comment]
Closed by #186
