### ISSUE TITLE
Some twts gets detached from the conversation

### ISSUE THREAD

**Issue by dooven** [jointwt/twtxt#194]
**Describe the bug**
This twts https://twtxt.net/conv/pkd2rta belongs to a conversation. But when you click the conversation button, it seems like it doesnt know about the parent conversation

**To Reproduce**
![out](https://user-images.githubusercontent.com/15314237/92986775-83a46d00-f47a-11ea-8ce6-65d1f6342363.gif)

**Expected behavior**
Clicking the conversation button should 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: LInux Mint

**Smartphone (please complete the following information):**
 - Browser Google Chrome

**Comment by prologic** [comment]
I _think_ between the two of us we fixed this now right?

**Comment by dooven** [comment]
Oh yeah this should be fixed.
