### ISSUE TITLE
[Mobile App]: Native iOS App (invite-only)

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#24]
**NB:** I am not a Mobile App developer nor have I ever attempted to write one.

This issue is to discuss and explore the options available for writing and publishing a Mobile App for iOS and Android for twtxt that uses a _yet-to-be-written_ API.

**Comment by flavienbwk** [comment]
Should this app be proposing an "endpoint url" at first launch (like Nextcloud is doing for user's own instance) or connect directly to the "official" online twtxt API?

My personal choice would be the first option.

**Comment by prologic** [comment]
That's an excellent question and I'm glad you brought it up here! Yes it will and should provide a way to enter the instance you wish to connect to. For ease of use it might have a default instance, because I can't imagine many non-technical folks would know immediately they can run their own.

**Comment by prologic** [comment]
Same would be true of the Desktop App in #23

**Comment by aaadonai** [comment]
I am interested to help with an iOS app. I like the idea of let you enter your instance too. As for default instances, Nextcloud iOS app does that in a nice way where they list default providers and let you login or sign up with them.

**Comment by prologic** [comment]
@aaadonai Nice! This would be really nice. How serious you  with doing this? What kinds of tech would you use? Webview based or native UI toolkits? I imagine you'd need to API to be rapidly built out as well to develop against?

**Comment by aaadonai** [comment]
@prologic I am an iOS engineer. I would build it native in Swift. Perhaps even using SwiftUI which I am learning at the moment. That could also help with the macOS version. I would need an API. What would be the best way for us to collaborate on specs for how the API should look like? Github issues for each endpoint?

BTW... I am @antonio on twtxt.net

**Comment by prologic** [comment]
@aaadonai Ahh brilliant you're [@antonio](https://twtxt.net/u/antonio) on [twtxt.net](https://twtxt.net)! Very nice :) Sl glad to have you onboard. 🤗

Now I'm going to have to defer to you re all things Mobile/iOS/etc as I knew next to nothing about it (_never got into it_). So I'm open to any kind of collab you see fit here, Google Hangout/Meet, Zoom, IRC (_I'm `@prologic` on FreeNode_), multiple Github issues might spam the issues  :) Or we could use [HackMD](https://hackmd.io/) to do some real-time (_depending on TZs_) on a API spec. Up to you :)

Are we okay with a JSON over HTTP API (_mostly RESTful_). I want to keep things fairly simple and as this is designed to be **decentralised** (_I made a horrifying typo on a Show HN post on v0.0.06 :/_) a single instance doesn't need to be "Web Scale" :)

**Comment by aaadonai** [comment]
@prologic I think HackMD will work. I have created a [team](https://hackmd.io/team/mobile-twtxt). Let me put some thoughts together and I will be creating notes there. I am also open to collab over Zoom, etc. I think the API specs would be the first step and perhaps also some screen mock-ups.

**Comment by prologic** [comment]
Yeah I accepted! Thank you for starting this! Yes I agree, let's define what the API should look like first and some basic screen mockups. I had some initial ideas on this already, not too different from what you see on https://twtxt.net/ on the Web right now and I use it on mobile just using Safari right now; but maybe even a little simpler again :) Love to obviously hear your own ideas based on what you've seen/used so far and what you think would work well!

**Comment by aaadonai** [comment]
@prologic I have [started](https://hackmd.io/yqll3RMRSTmMSMg7OoP2dQ) to add to the API specs.

**Comment by prologic** [comment]
repo created. Private (_for now) until we get this going; but licensed under the terms of the MIT License.

**Comment by prologic** [comment]
@aaadonai `/api/v1/timeline` endpoint is up 🎉

**Sample:**

```#!sh
$ curl -v -o - -H "Accept: application/json" -H "Token: **** -d '{"Page": 1}' http://localhost:8000/api/v1/timeline
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8000 (#0)
> POST /api/v1/timeline HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.64.1
> Accept: application/json
> Token: ****
> Content-Length: 11
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 11 out of 11 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Set-Cookie: twtxt.net=**** Expires=Wed, 12 Aug 2020 01:51:11 GMT; Max-Age=864000; HttpOnly
< Vary: Accept-Encoding
< Date: Sun, 02 Aug 2020 01:51:11 GMT
< Content-Length: 397
<
* Connection #0 to host localhost left intact
{"tweets":[{"Tweeter":{"Nick":"kate","URL":"http://0.0.0.0:8000/user/kate/twtxt.txt"},"Text":"Hello!","Created":"2020-08-02T11:50:56+10:00"},{"Tweeter":{"Nick":"james","URL":"http://0.0.0.0:8000/user/james/twtxt.txt"},"Text":"Hello World!  ![](http://0.0.0.0:8000/media/JcbHdtMLCEEUPcxoB3QAkc.png)","Created":"2020-08-02T08:49:45+10:00"}],"Pager":{"current_page":1,"max_pages":1,"total_tweets":2}}* Closing connection 0
```

Things that work:

- Everything you see on the [Timeline](https://twtxt.net) view now when logged in.
- Including paging through

Enjoy! 😎

**Comment by aaadonai** [comment]
We have made some progress on the iOS app and a version is available in private beta via TestFlight. If anyone is interested to testing it and give feedback you should contact me via [twtxt.net](https://twtxt.net). I am `@antonio` there.
With version 1.0(1) you can: Login, view your timeline and post. The timeline doesn't parse the markdown yet. But that should be coming on the next version this Sunday (8/16).

**Comment by aaadonai** [comment]
While the iOS app still been baked 😉 ! @dooven has just open source a [flutter app](https://github.com/jointwt/goryon) that works for iOS and Android. If anyone need an invite for the beta test on iOS let me know in the comments below or use [this link for the Android beta](https://play.google.com/apps/testing/com.jointwtxt.goryon).

**Comment by prologic** [comment]
As this is going  GA this week I'm closing this.
