### ISSUE TITLE
How to make discoverability via user agents work again? (Proposal)

### ISSUE THREAD

**Issue by vain** [jointwt/twtxt#244]
The one thing where twtxt.net truly *breaks* with the original model, is user agents. All I get from you is this:

    twtxt/0.1.0@64cf2e5 (Pod: twtxt.net Support: https://twtxt.net/support)

So there’s no way for me to know which users on that pod are following me. In the long run, this “coerces” users to join that pod instead of doing self-hosting. Because if I don’t join, I live in my own little bubble, while users of your pod still get the benefit of being notified about me following them.

Here’s a proposal on how this could be improved.

* Use a user agent like this: `twtxt/0.1.0@64cf2e5 (Pod: twtxt.net/following_external/$my_twtxt_url/$secret Support: https://twtxt.net/support)`
* When I see that in my access.log, I can open `https://twtxt.net/following_external/$my_twtxt_url/$secret` to retrieve a list of users on your pod that follow me. Preferably in a simple format like the one used in https://github.com/mdom/we-are-twtxt
* For privacy reasons, users on your pod should get a check box: “Do not expose my identity to external feeds.” This would emulate the behaviour of the original twtxt client.
* `$secret` should have a limited lifetime, so that if an attacker gets to know that URL, they won’t be able to spy on me *forever*.
* External users don’t need to create accounts on that pod, not even dummy ones just to be able to retrieve their list of followers.

Did I miss anything? I hope not. :)

**Comment by prologic** [comment]
Actually we discussed this before with in #35 and we _did_ make some beneficial changes (_or so I thought_), I'll have to go re-read that issue and figure out what we did or didn't do.

Full disclosure, I haven't read your OP fully yet, but I just want to say one thing first (_before I go have dinner and get back to this and answer more fully_);

We do want to make this as easy as possible, so yes you are right it is a bit hard and it shouldn't be. Some thoughts come to mind:

- Adding a list of URIs that follow you in the `User-Agent`. I never like this as it could get rather long...
- Adding an endpoint you can freely hit without any kind of authentication. e.g: /follows?uri=... which would return you a list of the Usernames and URIs of any user that follows the provided `uri` (_as long as they disclose this, it is user configurable_).

**Comment by prologic** [comment]
> So there’s no way for me to know which users on that pod are following me. In the long run, this “coerces” users to join that pod instead of doing self-hosting. Because if I don’t join, I live in my own little bubble, while users of your pod still get the benefit of being notified about me following them.

Ya know, you are welcome to also run the same software, that was the entire point of this project. I personally wasn't happy that I could not self-host my [micro.Blog](https://prologic.blog) "thing", but I do still like micro.Blog, it has its merits 👍 😀

**Comment by prologic** [comment]
> Here’s a proposal on how this could be improved.
> 
> * Use a user agent like this: `twtxt/0.1.0@64cf2e5 (Pod: twtxt.net/following_external/$my_twtxt_url/$secret Support: https://twtxt.net/support)`
> * When I see that in my access.log, I can open `https://twtxt.net/following_external/$my_twtxt_url/$secret` to retrieve a list of users on your pod that follow me. Preferably in a simple format like the one used in https://github.com/mdom/we-are-twtxt
> * For privacy reasons, users on your pod should get a check box: “Do not expose my identity to external feeds.” This would emulate the behaviour of the original twtxt client.
> * `$secret` should have a limited lifetime, so that if an attacker gets to know that URL, they won’t be able to spy on me _forever_.
> * External users don’t need to create accounts on that pod, not even dummy ones just to be able to retrieve their list of followers.

I _actually_ like this proposal quite a lot to be honest. It's probably the best proposal I've seen for this kind of thing!

The added use of a short-lived "secret" is also good -- prevents both abuse and misuse (_this information is really only for your eyes really_).

> Did I miss anything? I hope not. :)

Don't think so 😀

Did you want to implement list? My only ask if that the endpoint be `/follows?uri=&token=` and we use a query string parameter here because trying to properly encode things in the URL Path is just a giant PITA!

**Comment by vain** [comment]
> Actually we discussed this before with in #35

Oh, sorry, didn’t find that one. But now that you mention it: Back then, you guys discussed using new HTTP headers for this purpose. Not sure about that, I think it’s better to put the info in the user agent, because they are much easier to access (even in very simple web server setups). 

> Did you want to implement list?

Uhm, I have basically zero experience in writing Go. :(  If nobody gets around to doing it, I can try, but it would probably take a long time.

> My only ask if that the endpoint be `/follows?uri=&token=`

Sure, that would work just as well. :)

**Comment by prologic** [comment]
I can probably implement this tonight 😁

**Comment by prologic** [comment]
@vain i'm thinkingabout a 1 to 3 hour TTL on the token. What do you think? Or should it be configurable by the pod owner?￼

**Comment by vain** [comment]
I was originally thinking about a lifetime of a week or maybe a day, but I haven’t really given it much consideration, to be honest. Lower values are better for privacy, obviously.

Also depends on how people monitor their log files. For example, when people just do this:
```
ssh $my_server grep twtxt /var/www/logs/access.log |
sed -En 's#^[^"]+"GET /twtxt.txt[^"]+" 200 [0-9]+ "" "([^"]+)"#\1#p' |
sort |
uniq
```
Then they will get 24 lines per pod per day, if the TTL is 1h. Would they consider this to be spam? I don’t know. Not even sure if people monitor their logs in an automated way at all. I really have no idea about the common practice here.

The downside of my entire proposal is that you can’t get away with a simple `grep | sort | uniq` anymore. You’d need special handling for pods or you’ll see a lot of almost duplicate lines. I mean, it’s fine for me, I’d probably add a few lines of code that automatically grab the current list of followers from twtxt.net.

Maybe it’s worth “formalizing” the format a little bit, so it could be reused by other implementations of hosted twtxt (are there any?!):

```
twtxt/0.1.0@a8c0b10 (~${url_with_list_of_followers}; ${free_text})
twtxt/0.1.0@a8c0b10 (~https://twtxt.net/follows?uri=&token=; Support: https://twtxt.net/support)
```

**Comment by prologic** [comment]
> I was originally thinking about a lifetime of a week or maybe a day, but I haven’t really given it much consideration, to be honest. Lower values are better for privacy, obviously.

The problem  with this kind of thing is it is a burden on the pod's resources. I have to store this somewhere for a period of time. The shorter the better here as its an optimization measure. Most of how Twt.social pods work is by using primarily in-memory caching so a) Pods are memory bound and b) They are highly optimized as such.

> Maybe it’s worth “formalizing” the format a little bit, so it could be reused by other implementations of hosted twtxt (are there any?!):

Not that I am aware of, there was [this project](https://github.com/plomlompom/htwtxt) but it AFAICT was just a quick implementation and single-user. There are no known hosted instances of that software that I'm aware of. Plus it doesn't have anywhere near the feature-set we built here.

**Comment by prologic** [comment]
The other thing that _can_ be done here btw is for there to be an endpoint you implement where we can hit to say "hey you have a new follower".

I blogged about some of the things we did to improve/extend the Twtxt format/spec itself without breaking it in [Making Twtt Better](https://twtxt.net/blog/prologic/2020/10/18/making-twtxt-better), however I did not talk about the fact we implemented WebMentions, which is what I consider a "protocol" level change. Any Twt given its permalink URI (e.g: https://twtxt.net/twt/j2ew63a) can be WebMention'd. We also use this to also do cross-pod mentions as well.

Just an idea though... If you have a add a few lines to parse your log files for _special_ `User-Agent` strings, then hit an outbound endpoint, query it with say `jq`, you may as well just implemented an endpoint we can hit ourselves with a simple payload, much like WebMentions itself?

**Comment by prologic** [comment]
Or we _could_ do both :)

**Comment by prologic** [comment]
Btw, FWOW I'm _willing_ to bet that we have the same/similar problem as you:

https://github.com/jointwt/twtxt/blob/a8c0b1020e71a0ab3e109dbc00758ffe1b0044ed/internal/handlers.go#L575-L578

If I go look at the logs of my pod, I'll probably find this gets hit more often than I'd like. I should probably put a counter around it so I can measure it.

**Comment by prologic** [comment]
@vain Just wondering how secure these "tokens" need to be? Would [this library](https://github.com/marksalpeter/token/tree/master/v2) be sufficient? Base63 encoded uint64(s), with an in-memory cache and short-ttl of say ~1h?

**Comment by vain** [comment]
> The other thing that can be done here btw is for there to be an endpoint you implement where we can hit to say "hey you have a new follower".

Hmmmmmmmmmmmmmmmmmmmmmmm.

How about:

When a user on a pod starts following an external source, the pod requests the twtxt.txt file of that external source *once* and uses a full “traditional” user agent for this one request.

(Just to clarify, by “traditional user agent”, I mean something like `twtrd/latest (+https://www.uninformativ.de/twtxt.txt; @vain)`.)

This would a) be almost fully compatible with the original twtxt, thus b) would not require any adjustments to existing clients or log parsers, and c) would eliminate the need for maintaining `$secret` and all that.

I say “almost fully compatible”, because external users get that information only once, wheres the orignal twtxt sends it over and over again (every time the other user pulls your feed). So, as an external user, I don’t know if someone is *still* following me. Can’t tell, yet, if this is an issue – and there’s always the option of adding a new `unfollow` event that works in a similar way.

What do you think? I have a slight tendency towards this proposal, I think.

> Just wondering how secure these "tokens" need to be? Would this library be sufficient? Base63 encoded uint64(s), with an in-memory cache and short-ttl of say ~1h?

uint64 meaning `2**64` possible tokens? That should be fine. My web server can’t possibly handle that many requests in an hour, so you can’t brute force them, so we’re good. :)

**Comment by prologic** [comment]
How about we compromise and implement the following:

- [ ] On the first follow request we add a traditional full `User-Agent` field in the headers for the user that just followed that feed in the usual form `(+URI; @Nick)`.
- [ ] On subsequent fetches from the feed cache, we list the usernames of users that are following this feed up to a maximum of 5 with an ellipsis and a URL to query the full list protected by a short-lived (1h) token as per above.

So subsequent requests would look like this:

```
User-Agent: twtxt/v1.0.0 (Pod: twtxt.net Followers: @prologic @kt84 @lukem @antonio @felixp and 7 more... https://twtxt.net/whoFollows?uri=...&token=... Support: https://twtxt.net/support)
```

What do you think?

**Comment by prologic** [comment]
> * [x]  On the first follow request we add a traditional full `User-Agent` field in the headers for the user that just followed that feed in the usual form `(+URI; @Nick)`.

Implemented with #247

**Comment by prologic** [comment]
> * [x]  On subsequent fetches from the feed cache, we list the usernames of users that are following this feed up to a maximum of 5 with an ellipsis and a URL to query the full list protected by a short-lived (1h) token as per above.

Done in #247

**Comment by prologic** [comment]
Okay @vain #245 and #247 now implement everything we've talked about here. Just need to test it. Or I can just ship it to prod and "Test in Prod" 🚀 (cc @dooven for comments/reviews)

**Comment by vain** [comment]
Very nice! Thanks a lot! ❤️
