### ISSUE TITLE
Add API endpoint for Settings

### ISSUE THREAD

**Issue by dooven** [jointwt/twtxt#251]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/jointwt/goryon/issues/39
**Describe the solution you'd like**
Create an api endpoint for settings so that users can change their settings through the app (or any api clients)

**Comment by prologic** [comment]
Are you okay for it to work like the web form handler? Basically an all-inclusive `/api/v1/settings` endpoint where one of more fiends are provided as "updates"?

So for example if the user wanted to change their avatar, they could select a photo from their camera roll or take a live photo and that would get sent along with the request as Base64 encoded bytes?

Backend would basically just update the user object with the new fields (_doesn't even care to see if they are different_) and if the `Avatar` field is non-nill would overwrite the old avatar (_after processing it_).

Sound okay?

**Comment by dooven** [comment]
Yeah i think that makes sense. I encode the data as multipart/form-data so that we dont have to encode the image as base64, and have the other fields as a form field
