### ISSUE TITLE
Add media upload endpoint to the api

### ISSUE THREAD

**Issue by dooven** [jointwt/twtxt#266]
**Is your feature request related to a problem? Please describe.**
We want to add the video upload feature to the app https://github.com/jointwt/goryon/issues/69, and we need the media upload to be included in the api endpoints

**Comment by prologic** [comment]
@dooven I'll try to work on this today... Please remind me again what the logic should be on the backend to support older Goryon clients in a backwards compatible way? I don't really want to break the app for existing users.

I want to modify the existing endpoint to use the async task processor going forward, but keep what's in place now for older clients for  photo/image uplaods.

I would expect the new version of Goryon to also use the task processor though for image/phpto uploads too.

**Comment by dooven** [comment]
To keep the backwards compatibility, i think we just need to keep the  `/upload` endpoint 
https://github.com/jointwt/goryon/blob/master/lib/widgets/common_widgets.dart#L319-L330

Then we can create the new `/media` endpoints and we can add the upload image & upload video feature using the new endpoint

**Comment by prologic** [comment]
To be consistent with the web handlers I _could_ keep the same endpoint but do something like this:

```#!go
// UploadMediaEndpoint ...
func (a *API) UploadMediaEndpoint() httprouter.Handle {
   return func(w http.ResponseWriter, r *http.Request, p httprouter.Params) {
      // Limit request body to to abuse
      r.Body = http.MaxBytesReader(w, r.Body, a.config.MaxUploadSize)

      // TODO: Kill this code when old_media_upload nears zero
      if r.UserAgent() == "" {
        // Do the old thing
        return
      }

      // Do the new thing
    }
}
```

What do you think?

**Comment by dooven** [comment]
Yeah that makes sense. The old version still sends a default user agent. I added a comment in here https://github.com/jointwt/twtxt/pull/274#discussion_r523831739
