### ISSUE TITLE
What is minify?

### ISSUE THREAD

**Issue by markwylde** [jointwt/twtxt#275]
**Describe the bug**
I am trying to build from source so I can make some changes on my local machine without having to rely on docker.

But when I run make, it tells me `minify: command not found`

I'm guessing it should have been installed as part of the `make deps`?

**To Reproduce**
Steps to reproduce the behaviour:
```bash
[mark@mark-librem15v4 twtxt]$ make deps
go: found github.com/GeertJohan/go.rice/rice in github.com/GeertJohan/go.rice v1.0.0
go: github.com/akavel/rsrc upgrade => v0.9.0
go: github.com/valyala/fasttemplate upgrade => v1.2.1
go: github.com/daaku/go.zipexe upgrade => v1.0.1
go: github.com/nkovacs/streamquote upgrade => v1.0.0
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: golang.org/x/sys upgrade => v0.0.0-20201116194326-cc9327a14d48
go: github.com/spf13/pflag upgrade => v1.0.5
[mark@mark-librem15v4 twtxt]$ make
/bin/sh: minify: command not found
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Manjaro (ArchLinux)

**Smartphone (please complete the following information):**

**Additional context**
How do you install minify? What is the project?

**Comment by markwylde** [comment]
I was able to fix this manually by installing it in my package manager manually:

```bash
yay -Syu minify
```

**Comment by markwylde** [comment]
Actually it turns out GO's bin path wasn't added to my PATH:

```bash
PATH=$PATH:~/go/bin
```
Fixed it. Can we/Should we add this to the part of make that installed GoLang?

**Comment by prologic** [comment]
It's there already 👍

```#!sh
deps:
	@go get -u github.com/GeertJohan/go.rice/rice
	@go get -u github.com/tdewolff/minify/v2/cmd/...
```

Just run `make deps` :D

**Comment by prologic** [comment]
But yes you also _should_ add `$GOPATH/bin` to your `$PATH`

I'm a Go developer so :)

**Comment by markwylde** [comment]
But is the idea of `make deps` and `make` that you run those two commands on a fresh machine with nothing installed, and it will work it all out for you?

**Comment by prologic** [comment]
Yes! You need not run `make deps` a second time. 😁

**Comment by markwylde** [comment]
Okay I think I get the confusion. I thought `make` was installing `golang` for me. But it turns out I had it installed already just not added to my PATH.

I'll close this issue as it's not relevant to twtxt :)

**Comment by prologic** [comment]
If I can make the development any easier for first-time contributors let me know 😁￼￼
