### ISSUE TITLE
Building instructions do not work in FreeBSD 

### ISSUE THREAD

**Issue by oevl** [jointwt/twtxt#277]
**Describe the bug**
Build process as stated in the README do not work in FreeBSD

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone repo
2. Run ```make deps```
4. See several errors

**Expected behavior**
Successful build process of the ```twt``` and ```twtd``` packages.

**Screenshots**
![Error messages](https://user-images.githubusercontent.com/174772/99869750-718e2b80-2b9b-11eb-868a-5b0c91ca9475.png)

**Desktop (please complete the following information):**
 - OS: FreeBSD
 - Browser: Not applicable
 - Version: 12.1

**Smartphone (please complete the following information):**
 - Device: Not applicable
 - OS: Not applicable
 - Browser Not applicable
 - Version Not applicable

**Additional context:**

**Comment by prologic** [comment]
Nice!
