### ISSUE TITLE
Add domain next to user

### ISSUE THREAD

**Issue by markwylde** [jointwt/twtxt#284]
![image](https://user-images.githubusercontent.com/5929807/100718792-79ee2e00-3407-11eb-92a9-e9bdb98b0bff.png)

Add the domain a user is from beside the username:

- [ ] Add to the twt posting screen
- [ ] Add to the users profile

**Comment by markwylde** [comment]
@prologic can assign this one to me and I'll try and get it done this week.

What variable can I use in the template interpolation to get the domain?

**Comment by prologic** [comment]
Yeah I _think_ we want to only show this for "external" users/profiles anyway.

The other thing that Kory mentioned was on the timeline view itself to visually indicate somehow the difference between a local user and external user.
