### ISSUE TITLE
Use RFC 3339 timestamp format for tweet hash

### ISSUE THREAD

**Issue by der-lyse** [jointwt/twtxt#286]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement your twt hash algorithm in Python for my client in order to recreate a conversation view and currently fail to reliably format the timestamp. As it turns out [`Twt.Hash()`](https://github.com/jointwt/twtxt/blob/master/types/twt.go#L146) relies on Go's [`Time.String()`](https://golang.org/pkg/time/#Time.String) function which includes abbreviated time zone names such as `CET` (Central European Time) or `CEST` (Central European Summer Time) and the like. Formatted timestamps are e.g. `"2020-12-06 20:20:35 +0100 CET"` or `"2020-08-06 20:20:35 +0200 CEST"`.

I'm not sure where Go's standard library gets those information, as to my knowledge there's by no means a standardized bidirectional mapping between the UTC offset `+01:00` and the time zone name `CET`. [UTC+1](https://en.wikipedia.org/wiki/UTC%2B01:00) could also be `BST` (British Summer Time), `WAT` (West Africa Time), and many more. This is true for many (if not most) time zone offsets.

Additionally governments randomly change their time zone definitions, so it's not very reliable to include the time zone name in this hash calculation.

**Describe the solution you'd like**
Since the [twtxt file format specification already states that timestamps in the twtxt file have to be RFC 3339-formatted](https://twtxt.readthedocs.io/en/latest/user/twtxtfile.html#format-specification), I propose to reuse that format for the twt hash calculation instead. A more concise timestamp format is also more in the spirit of simplicity.

The [`Time.String()`](https://golang.org/pkg/time/#Time.String) docs also say, that this function is intended for debugging uses, so switching to a well-defined time format (I leave the *exact* RFC 3339 format decision up to you) would be beneficial to everybody adopting your brilliant invention of twt hashes:

> The returned string is meant for debugging; for a stable serialized representation, use t.MarshalText, t.MarshalBinary, or t.Format with an explicit format string.

I didn't take a deeper look into your code base, but I'm pretty sure this proposed change is backwards-incompatible and breaks old conversations. So I'm not sure whether this is something you are willing to change. However, I'm not sure whether the `Time.String()` documentation also means that the exact string representation of `Time.String()` is subject to change in future Go versions or not. If so, it might break stuff in the future anyways, so it might be best, to break things early with a smaller user base.

In any case, thank you very much for your efforts on developing twtxt in general!

**Describe alternatives you've considered**
* I've considered maintaining a hardcoded mapping myself, but this probably eventually breaks down, so I rather avoid that.
* GNU `date(1)` seems to be able to also generate at least `CET` and `CEST`, but I'm not totally keen on loading off the formatting to an external program such as `date(1)` or a dedicated Go program.

**Comment by prologic** [comment]
> Since the [twtxt file format specification already states that timestamps in the twtxt file have to be RFC 3339-formatted](https://twtxt.readthedocs.io/en/latest/user/twtxtfile.html#format-specification), I propose to reuse that format for the twt hash calculation instead. A more concise timestamp format is also more in the spirit of simplicity.

We already format timestamps this way:

```#!sh
prologic@Jamess-iMac
Mon Dec 07 10:43:15
~/Projects/jointwt/twtxt
 (master) 0
$ sift 'time.RFC3339'
internal/conversation_handler.go:68:                when := twt.Created.Format(time.RFC3339)
cmd/twt/ui.go:55:           twt.Created.Format(time.RFC3339),
internal/blog_handlers.go:100:              when := twt.Created.Format(time.RFC3339)
internal/media_handlers.go:73:              etag := fmt.Sprintf("W/\"%s-%s\"", r.RequestURI, fileInfo.ModTime().Format(time.RFC3339))
internal/cache.go:382:              Lastmodified: time.Now().Format(time.RFC3339),
internal/stats.go:28:func (o *TimeVar) String() string { return fmt.Sprintf("%s", o.v.Format(time.RFC3339)) }
internal/handlers.go:487:                   etag := fmt.Sprintf("W/\"%s-%s\"", r.RequestURI, fileInfo.ModTime().Format(time.RFC3339))
internal/handlers.go:881:           when := twt.Created.Format(time.RFC3339)
internal/handlers.go:1689:          etag := fmt.Sprintf("W/\"%s-%s\"", r.RequestURI, fileInfo.ModTime().Format(time.RFC3339))
internal/handlers.go:2059:                  etag := fmt.Sprintf("W/\"%s-%s\"", r.RequestURI, fileInfo.ModTime().Format(time.RFC3339))
internal/twt.go:137:                now.Format(time.RFC3339),
internal/twt.go:339:        // Twtxt clients generally uses basically time.RFC3339Nano, but sometimes
```

🤔

**Comment by prologic** [comment]
I'm responding to your OP in parts...

You basically have to port the following to Python:

https://github.com/jointwt/twtxt/blob/db4bf16471dbe6d68eab4cbc8676f2a167daeb3f/types/twt.go#L140-L155

Basically you perform the following steps:

1. Concatenate Twter's URL (i.e: the person that write the Twt) + timestamp + text (_separated by new lines_)
2. Hash this with Blake2b 256 Sum
3. Convert this to base32 (lowercase)
4. Take the last 7 characters

if you show me your client / source I can probably help!

**Comment by der-lyse** [comment]
Thank you for your quick response, @prologic!

> We already format timestamps this way:

Yes, but not in the `Twt.Hash()` function. As you quoted above, line 146 says:

```go
payload := twt.Twter.URL + "\n" + twt.Created.String() + "\n" + twt.Text
```

Here, `twt.Created.String()` is used rather than `twt.Created.Format(time.RFC3339)`. This generates something like `2020-12-06 20:20:35 +0100 CET` for the timestamp part instead of `2020-12-06T20:20:35+01:00`. Please note the `CET` in the former result which is not present in the RFC 3339 output.

For what it's worth, [the list of time zone abbreviations](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) show all the mess. Abbreviations themselves aren't even unique. /o\ It's just the current timestamp serialization that I'm struggling with, the rest of the algorithm is clear and works beautifully.

In case you're willing to accept the proposed change to the timestamp format in the twt hash calculation one could say that the RFC 3339 format is only used with timestamps from 2021-01-01 00:00:00 UTC on (or any other magic point in time). Timestamps prior to that would still use the existing timestamp format to keep old conversations intact. I'm not totally sure if the complication is worth it, but people probably enjoy some kind of backwards compatibility. Disclaimer: I haven't thought this fully through, it's just a crude idea. I could try to come up with a pull request, if you like the idea.

**Comment by prologic** [comment]
Oh damnit that's a bug! Do you want to fix this?

**Comment by der-lyse** [comment]
Sure, I can work on this. Due to some real world stuff I probably won't start with that until the end of the week, so don't expect a PR tomorrow. :-) What do you think about the "magic" date to smooth the transition?

**Comment by prologic** [comment]
> Sure, I can work on this. Due to some real world stuff I probably won't start with that until the end of the week, so don't expect a PR tomorrow. :-) What do you think about the "magic" date to smooth the transition?

I'm not sure I'd bother about the magic tape transition myself… What's the worst that could happen if we didn't?￼

**Comment by der-lyse** [comment]
> I'm not sure I'd bother about the magic tape transition myself…

Even better!

> What's the worst that could happen if we didn't?

Already existing conversations probably break. Other than that, it should be fine. I didn't look in the code yet, but I reckon the very first twt starting the conversation – to which the other twts were replied to using the subject – won't show up anymore. When playing around locally with the server code from a couple days ago it even looked like that an artificially crafted subject would not be recognized as a conversation at all, even though there were twts having the same subject. (However, the tag search worked.) Perhaps my assumptions do not hold or I had done something wrong. I didn't investigate, I just noticed that.

I'll keep you posted.

**Comment by prologic** [comment]
You are correct, a Conversation is only valid if the hash addreses a real Twt, whether in the active cache or archive.

**Comment by prologic** [comment]
But searching on hashtag(s) has no such restriction.
