### ISSUE TITLE
Could twtxt run on Github pages?

### ISSUE THREAD

**Issue by yibie** [jointwt/twtxt#289]
Could twtxt run on Github pages? Like hugo.

**Comment by prologic** [comment]
Yes. Strictly speaking you can host a [twtxt.txt](https://twtxt.readthedocs.org) file on Github Pages or literally any hosting provider or web server.

I did so in the early days when I first came across Twtxt [here](https://prologic.github.io/twtxt.txt).

These days I use [twtxt.net](https://twtxt.net) (_one of many such pods_).

**Comment by prologic** [comment]
If you decide to particiate in the ever-growing Twtxt community this way, I _recommend_ you also have a [config.yaml](https://twtxt.net/user/prologic/config.yaml) and [avatar.png](https://twtxt.net/user/prologic/avatar.ong) next to your feed so Twt.social pods can pick these up and display a pretty mug-shot of yourself 😀

**Comment by prologic** [comment]
The only downside there's no API and no mobile app access￼￼

**Comment by prologic** [comment]
Closing as I feel I've answered this question 😀 LMK if you have any further questions, feel free to create a conversation on my pod over at https://twtxt.net/ -- It doesn't matter how you join Twtxt 🤗

**Comment by yibie** [comment]
Thx, it works.

**Comment by prologic** [comment]
> Thx, it works.

And your URI is? :D
