### ISSUE TITLE
make deps failed: "undefined: coff.NewRDATA"

### ISSUE THREAD

**Issue by SnorlaxGengar** [jointwt/twtxt#290]
**Describe the bug**
make deps failed.

**To Reproduce**
1. git clone https://github.com/prologic/twtxt.git
2. make deps

**Expected behavior**
Install required dependencies success.

**Screenshots**
```bash
$ go get -u github.com/GeertJohan/go.rice/rice
go: found github.com/GeertJohan/go.rice/rice in github.com/GeertJohan/go.rice v1.0.0
go: github.com/daaku/go.zipexe upgrade => v1.0.1
go: github.com/nkovacs/streamquote upgrade => v1.0.0
go: github.com/akavel/rsrc upgrade => v0.10.1
go: github.com/valyala/fasttemplate upgrade => v1.2.1
# github.com/GeertJohan/go.rice/rice
../../go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/rice/embed-syso.go:188:13: undefined: coff.NewRDATA
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS and Windows 10

**Additional context**
Maybe it's depend library "github.com/akavel/rsrc/coff" lead to this problem? https://github.com/akavel/rsrc/commit/6c59b92bada085ce1b7ad670435ffe594b4a2656

**Comment by prologic** [comment]
Thanks for reporting! I'll follow this upstream, looks like the tool is broken and `go get` is not capable of installing a particular version of a binary 😢

This tool is only needed to re-generate the `rice-embed.go` in `./internal` anyway which we commit to the source tree, so `make buidl` _should_ still work. Can you confirm?

**Comment by SnorlaxGengar** [comment]
It works for me, thanks! Great job!

**Comment by prologic** [comment]
I will close this once the upstream issue on go-rice is resolved.

**Comment by prologic** [comment]
Fixed with https://github.com/GeertJohan/go.rice/commit/0634379bb7b1af96fb16686afc301ae7ae9ee8b9
