### ISSUE TITLE
Posting markdown links with anchor in URL interperprets anchor as tag

### ISSUE THREAD

**Issue by der-lyse** [jointwt/twtxt#300]
**Describe the bug**
Posing via the web user interface causes the URL in a markdown link to be mangled up if it contains an anchor part. The anchor part is wrongly recognized as a tag and fully expanded to a twtxt link markup.

**To Reproduce**
1. Post a twt using the web interface, such as:
```This twt reproduces the bug: [Oh no](https://example.com/#foo)```
2. Notice, that in the user's _twtxt.txt_ file the twt text says:
```This twt reproduces the bug: [Oh no](https://example.com/#<foo http://0.0.0.0:8000/search?tag=foo>)```
3. The web interface is also not able to render the link correctly, the `href` is missing entirely.

**Expected behavior**
The anchor part is preserved as entered by the user when posting.

**Comment by prologic** [comment]
Yup this is a bug. The regex needs to be fixed "somehow". Are you able to put up a PR for this maybe?

**Comment by der-lyse** [comment]
I can try, but I'm not 100% certain that using regexes for this is really the way to go forward. Maybe a tokenizer would be better.

I'll have a look at the code though.

**Comment by prologic** [comment]
I _thnk_ you're right, I think this is one of those cases where a regex won't work. Regular vs. Irregular languages.

**Comment by der-lyse** [comment]
I reckon it's easiest to properly fix when JonLundy's new lexer is ready. I always keep getting stuck.

**Comment by prologic** [comment]
> I reckon it's easiest to properly fix when JonLundy's new lexer is ready. I always keep getting stuck.

I agree, this isn't something that's easily fixed with regex.
