### ISSUE TITLE
Rendering of Markdown links with anchors in URL is broken

### ISSUE THREAD

**Issue by der-lyse** [jointwt/twtxt#301]
**Describe the bug**
Twts containing Markdown links with anchored URLs result it in a broken rendering on the web user interface. The links point to nowhere.

**To Reproduce**
1. Post a twt containing a markdown link with an anchor in the URL, such as:
```This twt reproduces the bug: [Oh no](https://example.com/#foo)```
(**Warning:** to work around #300, do this in the _twtxt.txt_ file directly or use a client which preserves the raw twt text)
2. Have a close look at the rendering.

**Expected behavior**
The twt is rendered with a single hyperlink titled `Oh no` pointing to `https://example.com/#foo`:
either ```<a href="https://example.com/#foo">Oh no</a>```
or ```<a href="https://example.com/#foo" target="_blank">Oh no</a>```

**Actual behavior:**
The twt is rendered with a single hyperlink titled `On no` pointing to nowhere:
```<a target="_blank">Oh no</a>```

**Comment by prologic** [comment]
I _think_ this is the same problem as #300

**Comment by der-lyse** [comment]
Indeed, this is resolved by #314 (partial fix for #300) as well.

**Comment by prologic** [comment]
> Indeed, this is resolved by #314 (partial fix for #300) as well.

Thank you for that PR! 🙇‍♂️ This is fantastic go see more contributions from the community! 🤗 (_FYI merges get pushed out automatically and re-deployed within a few mins_)

**Comment by der-lyse** [comment]
> Thank you for that PR! bowing_man This is fantastic go see more contributions from the community! hugs

Sure, no worries mate. ;-)

> (_FYI merges get pushed out automatically and re-deployed within a few mins_)

Nice! \o/

(Oh, I didn't know I could close this bug report, I assumed a repo owner must do that. I just noticed the "Close with comment" button, thus, closing this ticket now.)

**Comment by prologic** [comment]
> (Oh, I didn't know I could close this bug report, I assumed a repo owner must do that. I just noticed the "Close with comment" button, thus, closing this ticket now.)

Yeah that's a feature of Github with Issue references.
