### ISSUE TITLE
Rendering of twtxt link markup without a title treats last character as URL

### ISSUE THREAD

**Issue by der-lyse** [jointwt/twtxt#302]
**Describe the bug**
I'm currently writing documentation on the twtxt link markup and twtxt subject extensions and while experimenting around, I discovered that twtxt links without titles (or without URLs) are rendered very weirdly in the web user interface.

**To Reproduce**
1. Post a twt with a twtxt link markup, such as:
```This reproduces the bug: #<https://example.com/bar>```
2. Observe the rendered result.

**Expected behavior**
Although it's probably not defined what should happen if a twtxt link does not contain a title, I certainly would not expect the current behavior, but something along those lines:
1. A link to the URL with its title/text being the same URL (my preferred one), e.g.:
```<p>This reproduces the bug: <a href="https://example.com/bar">https://example.com/bar</a></p>``` (The HTML anchor tag might have additional attributes, such as `target` or `rel`.)
2. Not a twtxt link at all, just verbatim text with angle brackets escaped properly:
```<p>This reproduces the bug: #&lt;https://example.com/bar&gt;</p>```

**Actual behavior**
Since this is invalid HTML, it is clearly a bug:
```<p>This reproduces the bug: <a href="r" rel="nofollow">#<a href="https://example.com/ba" target="_blank" rel="nofollow noopener">https://example.com/ba</a></a></p>```
To me it looks like the link text of the outer HTML anchor is processed a second time (maybe to render plain URLs) and thus the inner HTML anchor is generated.

Please note, that the last character of the original URL is removed and taken as the URL while the remaining prefix is the link text. This becomes more obvious if one uses a twt text, such as:
```#<eggs-and-spam>```
which will become:
```<p><a href="m" rel="nofollow">#eggs-and-spa</a></p>```

**Additional context**
I'm not sure what to do with twtxt links which contain only one part, either the title or the URL. In my own twtxt client I treat it is a URL with no text if it starts with `http://` or `https://` (the parsed twtxt link token will then be rendered with the URL as the link text down the road). In all other cases it's just a link text without a target URL. Text without URL works quite well in the txtxt subject for my conversation grouping, somewhere else in the text not so much.

The guessing could be improved to recognize anything containing `://` as a URL. My only motivation for allowing a "short form" in the first place is to make twtxt hashes in the twtxt subjects shorter, so e.g. ```@<nick url> (#<hash>) bla bla``` works, too. However, I haven't seen this in the wild, it's just an idea to save space and bandwidth. In order to form my conversation tree, I just rely on the hash itself (the `title` part in the `#<title url>`) and completely ignore the URL so to speak.

My Python twtxt text parser is far from perfect and has a couple of known issues regarding subject recognition (not a problem in the wild, though) and apart from markdown links there's nothing markdowny else it supports, but it generates a stream of tokens good enough for me so far. I will try to polish it a bit and then release it to the wild, if that is something which might help.

**Comment by prologic** [comment]
Yeah good catch. PR is welcome to fix  this!

**Comment by der-lyse** [comment]
FYI [here's my tokenizer I talked about earlier](https://git.isobeef.org/lyse/tt/-/blob/master/twtxtparser.py). I didn't polish it, though.

What's your take on single part twtxt links? I can also create a PR for my extension docs once I finish them and we discuss it over there. Then we can fix this bug accordingly.

**Comment by prologic** [comment]
> What's your take on single part twtxt links?

I'm not sure ot be honest. I'd just display it full in that case with the url as the title?

**Comment by prologic** [comment]
Is this still an issue?

**Comment by der-lyse** [comment]
No, now the twt text from above renders a hash tag only, but with the correct URL in the anchor's href. So this bug can be considered fixed I reckon.

**Comment by prologic** [comment]
I think @JonLundy fixed it with the new parser 🙇‍♂️

**Comment by der-lyse** [comment]
I think so, too.
