### ISSUE TITLE
Twt Subject Extension

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#308]
Like [Twt Hash Extension](https://dev.twtxt.net/doc/twthashextension.html) let's also document the "Twt Subject Extension" that came about with this work.

This is important as along with Twt Hashes lets us group together multiple  Twts from one or more feeds into a "Conversation'.

This works even across pods and even with "traditional" twtxt clients.

@der-lyse Since you did such a great job of writing these specs, do you mind writing this one up too? :D

**Comment by der-lyse** [comment]
Sure, I was planning on doing that as well. It's just a matter of juggling time and getting in the right mood. :-)
