### ISSUE TITLE
Render issue with brackets at the following-page

### ISSUE THREAD

**Issue by sorenpeter** [jointwt/twtxt#335]
When look at following-page there is a issue with the render of brackets:
<img width="290" alt="Screenshot 2021-01-17 at 14 37 24" src="https://user-images.githubusercontent.com/8458421/105089826-e8617b00-5a9d-11eb-88b8-5f5b7e65947f.png">
The issue is not there on the followers-page

**Comment by prologic** [comment]
Thanks I'll take a closer look at this later this evening.
