### ISSUE TITLE
Apple's iOS 14.3 does not render WebP images correctly

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#337]
I had been debugging this for days and finally identified that Apple's iOS 14.3 **does not** render WebP images correctly.

The work-around is to check to see if the `User-Agent` is `iPhone OS 14_3` and if the for an `Accepts: image/webp,...` and ignore this as it doesn't work. Until Apple fix the bug, WebP __does not__ work on iOS 14.3 despite the fact they obviously added support for it and it is listed in [Can I use X](https://caniuse.com/webp)

![signal-2021-01-20-122647](https://user-images.githubusercontent.com/1290234/105118984-20f36a00-5b1b-11eb-91fb-797663e5fa3d.jpeg)

**Comment by xHeinrich** [comment]
We were running up against the same issue on a shopify store in a mini react app, we identified the issue down to being some compression issue with solid colored images and only triggers if we dynamically update an images src via javascript. If we added some detail to the image such as a large red star on a white background it would function again.

**Comment by prologic** [comment]
No action we can take here but will need to retest in new versions of iOS in future
