### ISSUE TITLE
A case for Matrix over Mastodon nick and server convention

### ISSUE THREAD

**Issue by sorenpeter** [jointwt/twtxt#346]
It just looks silly and confusing with two @-sign !

Now I can't remember where in the UI of twt.social I saw it spelled out like `@sorenpeter@darch.dk` but i find it much cleaner to have it say `@sorenpeter:darch.dk` even thou  it is fairly new convention for everyone to get use to.

<img width="382" alt="Screenshot 2021-01-21 at 17 08 23" src="https://user-images.githubusercontent.com/8458421/105377629-4bbceb80-5c0b-11eb-95d6-ba9ad43b7848.png">

So any change we can change it to a colon  like they use in matix.org ?

<img width="221" alt="Screenshot 2021-01-21 at 17 05 43" src="https://user-images.githubusercontent.com/8458421/105377650-54152680-5c0b-11eb-8fd7-fc079dab957e.png">

**Comment by sorenpeter** [comment]
It looks like the @nick@domain.net only shows up when editing a post/reply to a user with an external feed:
<img width="1159" alt="Screenshot 2021-01-21 at 17 19 13" src="https://user-images.githubusercontent.com/8458421/105379411-16190200-5c0d-11eb-9951-3bdb4ab73934.png">

**Comment by prologic** [comment]
> It looks like the `@nick@domain.net` only shows up when editing a post/reply to a user with an external feed:  
> 
> <img width="1159" alt="Screenshot 2021-01-21 at 17 19 13" src="https://user-images.githubusercontent.com/8458421/105379411-16190200-5c0d-11eb-9951-3bdb4ab73934.png">

It actually doesn't work for traditional External twtxt feeds feeds at all Because it makes assumptions about the structure of a domain/url￼

**Comment by sorenpeter** [comment]
What syntax does not work? The @n@d or @n:d ?

Found this real life example: <img width="634" alt="Screenshot 2021-01-22 at 07 57 01" src="https://user-images.githubusercontent.com/8458421/105458354-acd6d480-5c88-11eb-940f-4ff9a14c9de8.png">

**Comment by prologic** [comment]
What I meant to say is that the syntax `@nick@domain` only works for pods. It doesn't work for traditional users of twtxt  that just host a `twtxt.txt` file  somewhere because it makes assumptions  about the hosting structure. e.g: in `twtd`  the backend quite literally assumes that `@foo@domain` translates to `https://domain/user/foo/twtxt.txt`. Make sense?

**Comment by sorenpeter** [comment]
Yes i'm aware this is a pod-thing:)  but is there any reason why this can't be change except for backward capability?

The scope here is only [Twt|Yarn].social but it could be extended to other implementations and way to communicate your feed/profile to others.

If the @n:d syntax is implemented the it would be nice to have it show up across the UI and not just in pseudo-random spots :)

**Comment by der-lyse** [comment]
Isn't the client supposed to translate this `@nick@domain` syntax to proper twtxt `@<nick url>` mention syntax before publishing?

**Comment by prologic** [comment]
> Isn't the client supposed to translate this `@nick@domain` syntax to proper twtxt `@<nick url>` mention syntax before publishing?

Yes. It's preprocessed.

**Comment by prologic** [comment]
This would only work in Luker implementations if we agreed on a URL structure

**Comment by prologic** [comment]
@sorenpeter I'm going to close this for now, if that's ok  :) I just don't _think_ there's enough of a compelling reason here at this time. We have so many bigger things to fry right now 🤣
