### ISSUE TITLE
Error when url to user ends with a slash

### ISSUE THREAD

**Issue by sorenpeter** [jointwt/twtxt#351]
Accessing https://twtxt.net/user/darch/ gives an error:

<img width="603" alt="Screenshot 2021-01-23 at 11 28 19" src="https://user-images.githubusercontent.com/8458421/105575781-5c39a700-5d6e-11eb-85b1-0107f9850ffd.png">

But if you remove the slash `/` at the end of the url it works fine:
<img width="528" alt="Screenshot 2021-01-23 at 11 28 27" src="https://user-images.githubusercontent.com/8458421/105575796-75daee80-5d6e-11eb-9bdf-85a0083cbfb1.png">

**Comment by prologic** [comment]
Okay seems legit 😁

**Comment by u5surf** [comment]
@sorenpeter @prologic 
Hi, It is a probably quite easy solution I have.
But I don't know whether or not this is a breaking changes.

```
diff --git a/internal/utils.go b/internal/utils.go
index 465caeb..0090599 100644
--- a/internal/utils.go
+++ b/internal/utils.go
@@ -1188,7 +1188,7 @@ func ParseURI(uri string) (*URI, error) {
 }
 
 func NormalizeUsername(username string) string {
-       return strings.TrimSpace(strings.ToLower(username))
+       return strings.TrimSpace(strings.ToLower(strings.TrimSuffix(username? "/")))
 }
 
 func NormalizeURL(url string) string {

```
