### ISSUE TITLE
Manage Pod Settings: Avatar

### ISSUE THREAD

**Issue by thewismit** [jointwt/twtxt#357]
The text on the Manage Pod settings page needs clarification.

Via the web client, the setting is "Change avatar", which to me, means user avatar. However, I thought maybe it means site logo. Upon changing the logo it doesn't seem to appear anywhere and my user avatar remains what it is set to.

It would be nice if this is meant to be a site logo, for the functionality to be implemented properly. If it is unintentionally misleading and is meant to be the user avatar, I think this setting should be removed from the Manage Pod settings.

**Comment by prologic** [comment]
I've been able to fix this and make it work (_the guy that built this feature didn't finish it :/_)

<img width="1312" alt="Screen Shot 2021-01-25 at 09 11 12" src="https://user-images.githubusercontent.com/1290234/105647609-9469f280-5ef2-11eb-902e-bc6f91178837.png">

But I have a question?

> Should we support only SVG? Or should we support both images PNG/JPEG as well as SVG(s)?

**Comment by prologic** [comment]
One problem I'm seeing with `image/png` for example is light and dark mode. It doesn't work very well.

**Comment by thewismit** [comment]
I think it best to support both png and svg. The look of the pod logo, however good or bad should be left to the owner.

Additionally some owners may not have access to a program the creates/converts to svg.

**Comment by prologic** [comment]
Hmmm
