### ISSUE TITLE
Twt hash reference implementation in `node`

### ISSUE THREAD

**Issue by vladimyr** [jointwt/twtxt#361]
https://github.com/jointwt/twtxt/blob/f18dfa2efc5c8c209bbf68f6bab15c7144d6f1e1/docs/_posts/2020-12-11-twthashextension.md#L83-L85

Here is my modest contribution to twt hash algorithm implementations in form of a `node` powered Repl.it _notebook_: https://repl.it/@vladimyr1/hash-twt

It is a bit hard to reduce it to a simple snippet because it heavily relies on external libs:
```js
const b32encode = require('base32-encode');
const blake2 = require('blake2');
```

I guess something along these lines might be a good fit:
```js
const b32encode = require('base32-encode');
const blake2 = require('blake2');

function base32(payload) {
  return b32encode(Buffer.from(payload), 'RFC3548', { padding: false })
    .toLowerCase();
}

function blake2b256(payload) {
  return blake2.createHash('blake2b', { digestLength: 32 })
    .update(Buffer.from(payload))
    .digest();
}

const payload = [feedUrl, twt.createdAt, twt.content].join('\n');
const hash = base32(blake2b256(payload)).slice(-7);
```

What do you think, is it PR ready material? :upside_down_face:

**Comment by prologic** [comment]
I think a PR is definitely worthwhile here 👌 Maybe in `contrib/`?

**Comment by vladimyr** [comment]
I was thinking of adding it to referenced docs page. What do you suggest putting inside contribs, complete npm package? 🤔

**Comment by prologic** [comment]
Actually reference docs would be good I think 👌

We may have future plans of building libraries for handling twtxt + extensions in a generic way for at least Go, Pyhthon and Jacascdipt

**Comment by vladimyr** [comment]
Ok, PR is on the way 👨‍💻
