### ISSUE TITLE
Site Default Light Theme Broken? 

### ISSUE THREAD

**Issue by thewismit** [jointwt/twtxt#375]
**Describe the bug**
Unable to change site default theme to light. 

**To Reproduce**
Steps to reproduce the behaviour:
Changed the environment variable in the docker compose file to light and rebuilt the container. 

**Expected behavior**
Site should render using the light theme. It does not. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prologic** [comment]
I think 284a945 _might_ fix this. Can you confirm?

**Comment by prologic** [comment]
Pretty sure this is fixed 🤗
