### ISSUE TITLE
Ambiguous Regular Expression for Follow Detection (Linguee Incident)

### ISSUE THREAD

**Issue by mckinley360** [jointwt/twtxt#416]
I am not following the bug report template because I believe this issue would be difficult to explain well using it. I apologize if I should have done so.

First, a recap of the Linguee incident as I know it for anyone who is not familiar. On Sunday, April 11th, Linguee Bot, the web crawler for an online multi-language dictionary service, crawled twtxt.net. This would not normally have been a problem, but by crawling the user's twtxt feeds, 102 follow events were created. This clogged the Discover feed with 102 follow announcements from the twtxt bot, and now all of those users, including myself, have a "follower" that links to Linguee Bot's webpage.

I am not a programmer, but here's what I see. If you know what you're doing, please weigh in. From looking at the code it appears [/internal/utils.go](https://github.com/jointwt/twtxt/blob/master/internal/utils.go) is what handles the relevant part of the external follower system. The aptly named regex [userAgentRegex](https://github.com/jointwt/twtxt/blob/master/internal/utils.go#L110) is very permissive, and it will even match the string `<space>(http://<space>)`. (Replacing `<space>` with a space character)

The situation regarding Linguee Bot happened because its user-agent `Linguee Bot (http://www.linguee.com/bot; bot@linguee.com)` was a valid match for the regular expression when it shouldn't have been. I wrote the potential replacement below to try and stop this from happening in the future. The capturing groups are intentionally made to match the same parts of the string as the current regex.

`(.+) \(\+(https?://\S+/\S+); (\S+)\)`

This is more restrictive than the regex that's currently used and should make it more difficult for innocent web crawlers to cause us problems. However, it is still easy to break and should probably be made much more restrictive. Tell me what you think.

Here are links for [My Regex](https://regex101.com/r/n6KZG1/1) and the [Current Regex](https://regex101.com/r/5oA5Pt/1) if you want to test either of them on Regex101. Please try to break it in as many ways as you can think of and report back.

**Comment by prologic** [comment]
Thanks for an awesome report! I'll apply a fix tonight!
