### ISSUE TITLE
Hosted Pods (fully-managed, invite-only)

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#87]
We (_the twtxt.net team_) are busy working on lots of exciting things including:

- [An iOS native App](https://github.com/prologic/twtxt/issues/24)
- [Hosted Instances / Pods](https://github.com/prologic/twtxt/issues/87) (_we're probably going to call them pods_)
- [Desktop App](https://github.com/prologic/twtxt/issues/23)
- [Mentions and Notifications](https://github.com/prologic/twtxt/issues/13)
- [Custom Domains](https://github.com/prologic/twtxt/issues/37)
- and [much much more...](https://github.com/prologic/twtxt/issues) 🎉

If you are interested in trying this out and getting onboard early, please get in touch! We will be offering this as a limited invite-only beta to help build out the platform and iron out all the quirks.

**Comment by prologic** [comment]
📣 **ANN:** Just a quick update on this... This is has made progress. There is now an "alpha" version of the landing page where you can (_soon_) sign-up and create your own hosted pods by just filling out a form and hitting a button. Please let me (@prologic) know if you'd like to be a beta tester or would like to see what it looks like (_nothing works yet_). Thanks!

**Comment by prologic** [comment]
cc @aaadonai @dooven @shahxeb @lwojcik

**Comment by prologic** [comment]
📣 **ANN:** Introducing the first _alpha_ version of fully managed, 1-click hosted pods [twt.social](https://twt.social); of the same software that backs [twtxt.net](https://twtxt.net) 🎉 This means you can now request a pod of your own and get your own `yourname.twt.social` for yourself, your family or community. Please get in touch if you'd like to have one today! __Please Note:__ This is very early alpha and we invite all alpha testers to join! 🤗 Check it out! https://twt.social/

**Comment by robotamer** [comment]
Link isn't working. There is just an empty page. There is no form, or any request instructions.

**Comment by prologic** [comment]
> Link isn't working. There is just an empty page. There is no form, or any request instructions.

Apologies :/ We're moving really quickly on many fronts.

Which link in particular is giving you grief?

In the meantime send me an email via https://twtxt.net/support and I'll get you a token!

**Comment by prologic** [comment]
We're done with this. Next steps will be (_one day_) to charge a small nominal fee for hosting pods on behalf of pod owners (_users join free_). The nominal fee will be quite small, small enough that hosting/running a pod (_that [Twt.social](https://twt.social) will manage on behalf of_) will be accessible to (_hopefully_) anyone.

Of course, anyone technically adept at running and deploying software are welcome to do so on their own, for example [@etux](https://twt.u53.us/users/etux) over at [twt.u53.us](https://twt.u53.us).
